# Site settings
title: IOT
course_name: IOT
course_description: The internet of things, or IoT, is a system of interrelated computing devices, mechanical and digital machines, objects, animals or people that are provided with unique identifiers (UIDs) and the ability to transfer data over a network without requiring human-to-human or human-to-computer interaction.
course_semester: "Winter 2020"
description: |
    Instructor: soroosh mahdizadeh

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/IOT" # the subpath of your site, e.g. /blog/
url: "http://sorooshmz.github.io/IOT" # the base hostname & protocol for your site
syllabus: http://sorooshmz.github.io/IOT/syllabus/
githubdir: 

# Author/user information
email: soroosh_mahdizadeh@comp.iust.ac.ir
twitter_username: None
github_username:  sorooshmz
authorurl: "http://sorooshmz.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
